### ISSUE TITLE
Enable HA thermostat component UI

### ISSUE THREAD

**Issue by specsix** [timmo001/home-panel#269] opened 2019-04-12 10:08 UTC
# Description

- The up and down arrows only show if you make the card large enough and the temperature up and down arrows dont seem to be doing anything.  The circle slider does not appear.

## Suggested Actions
Pass through or implement the circle slider UI on long press.

## Additional

I am a UX react developer for Microsoft and would be willing to help with this if I could be onboarded quickly.

**Comment by timmo001** [comment] 2019-04-25 15:29
This is by design. If you increase the card size, the arrows will appear. The slider you are talking about is a Home Assistant Lovelace card. If you would like to help improve this, feel free to open a PR.

For now, I will close this issue since it is intended to work this way.

**Closed by timmo001** 2019-04-25 15:29 UTC
Labels: Closed: Expected behavior
