### ISSUE TITLE
Unnecessary scrolling appears on low res devices

### ISSUE THREAD

**Issue by sagilo** [timmo001/home-panel#139] opened 2018-10-24 18:00 UTC
# Description
I'm using Amazon Fire HD8 (1,280x800) and apparently, there is some scrolling with white background "below" the panel.
It happens both on portrait and landscape.
One of the columns has a scrollbar and every time I scroll it down the whole page is scrolled down as well.

## How to reproduce the issue (if applicable)
I was able to reproduce this issue on my mobile device (Samsung S7) only when 'Desktop Site' is OFF.
On my Amazon Fire HD8 it happens regardless to "Desktop site" state

## Screenshots (if applicable)
![screenshot](https://i.imgur.com/vSBqddq.png)

## Additional information
Running version v0.6.5
Using Chrome browser

**Comment by timmo001** [comment] 2018-11-28 10:56
I've recently got a new phone and am seeing this when scrolling the page down to gide the browser bar. I will take a look to see wht might be causing this. Thanks

**Comment by timmo001** [comment] 2018-12-29 16:58
> I've recently got a new phone and am seeing this when scrolling the page down to hide the browser bar. I will take a look to see what might be causing this. Thanks

This is an issue with the browser itself.

I still cannot reproduce the main issue with the devices I have on hand. It looks to be an issue with the device more than a scrolling issue. Closing this issue for now. If this can be reproduced and a fix found in the future. Please open a new issue. Thanks

**Closed by timmo001** 2018-12-29 16:58 UTC
Labels: Accepted, Type: Bug, User Interface
